apiVersion: v2
name: optryn-agent
description: Optryn Agent with Internal Prometheus and RBAC
type: application
version: 0.2.2
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
