# Agent Configuration
image:
  repository: asia-south1-docker.pkg.dev/poc-tc/k8s-agent/v1-agent
  tag: latest
  pullPolicy: Always

# Backend API base URL (kubernetes-service public URL)
apiBaseUrl: "https://k8s-api-v1.optryn.com"

# Will be set by install command
clusterId: ""
agentToken: ""

# Namespace + name controls
namespaceOverride: "optryn-system"
nameOverride: "optryn-agent"
fullnameOverride: ""

rbac:
  create: true

# Optional extra env
extraEnv: []
# - name: SCRAPE_INTERVAL_SECONDS
#   value: "60"
# - name: HTTP_TIMEOUT_SECONDS
#   value: "15"
# - name: LOG_LEVEL
#   value: "info"
# - name: PROMETHEUS_URL
#   value: "http://optryn-agent-prometheus-server.optryn-system.svc:80"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Bundled Prometheus Configuration (if you are packaging it as a dependency)
prometheus:
  enabled: true
  server:
    fullnameOverride: "optryn-agent-prometheus-server"
    persistentVolume:
      enabled: false
    global:
      scrape_interval: 1m
    retention: "1d"
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: true
  kubeStateMetrics:
    enabled: true
