apiVersion: v1
entries:
  optryn-agent:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-28T12:26:52.62584+05:30"
    dependencies:
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 25.8.0
    description: Optryn Agent with Internal Prometheus and RBAC
    digest: 96c6f63fae1aa6c4a968dac20dcd71a7219355cfbc44a7ebd86f748071cb304c
    name: optryn-agent
    type: application
    urls:
    - https://charts.optryn.com/charts/optryn-agent-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-12-28T12:26:52.622358+05:30"
    dependencies:
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 25.8.0
    description: Optryn Agent with Internal Prometheus
    digest: f9444a84838f19ee6a7b4869b3b6bdc69677651c2165fabbacd72ad5ce3a8426
    name: optryn-agent
    type: application
    urls:
    - https://charts.optryn.com/charts/optryn-agent-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-28T12:26:52.618152+05:30"
    dependencies:
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 25.8.0
    description: Optryn Agent with Internal Prometheus
    digest: 28e0c0080d7979aaa4b798b00207ea7667f965be2f792f4964b3eb33dc436c87
    name: optryn-agent
    type: application
    urls:
    - https://charts.optryn.com/charts/optryn-agent-0.2.0.tgz
    version: 0.2.0
generated: "2025-12-28T12:26:52.614501+05:30"
